// This code was generated by `SqlHydra.Npgsql` -- v3.6.0.
namespace EnergyMonitor.DbEnergy

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(3, 6, 0)
    let ns = "EnergyMonitor.DbEnergy"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

[<System.Obsolete("The HydraBuilders module is no longer needed and will be removed in v4.0.")>]
module HydraBuilders =
    ()


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        QueryContextFactory.Create(Npgsql.NpgsqlDataSource.Create(connectionString), ?sqlLogger = sqlLogger)

    static member Create(dataSource: Npgsql.NpgsqlDataSource, ?sqlLogger) =
        let compiler = SqlKata.Compilers.PostgresCompiler()

        let createConn () : System.Data.Common.DbConnection = dataSource.OpenConnection()

        let openContext () =
            let conn = createConn ()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let! conn = dataSource.OpenConnectionAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
